.PHONY: clean All

All:
	@echo "----------Building project:[ R_6_11_GenericNodeLIstClass - Debug ]----------"
	@cd "R_6_11_GenericNodeLIstClass" && "$(MAKE)" -f  "R_6_11_GenericNodeLIstClass.mk"
clean:
	@echo "----------Cleaning project:[ R_6_11_GenericNodeLIstClass - Debug ]----------"
	@cd "R_6_11_GenericNodeLIstClass" && "$(MAKE)" -f  "R_6_11_GenericNodeLIstClass.mk" clean
